name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install
        run: npm ci
        
      - name: lint
        run: npm run lint
        
      - name: compile to check syntax
        run: npm run check
        
      - name: run test
        run: npm run test
